/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.DataAccesUsuario;
import Conexion.DataBaseConnection;
import Entidades.Usuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Frm_Registrar_Usuario extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;

    /**
     * Creates new form Frm_Registrar_Usuario
     */
    public Frm_Registrar_Usuario() {
        try {
            conexion = DataBaseConnection.getInstancia().getConexion();
            st = conexion.createStatement();
            initComponents();
        } catch (SQLException e) {
            System.err.println("Error al crear el Statement: " + e.getMessage());
        }
        this.setSize(646, 540);
        DataBaseConnection.pantallaPrincipal.setVisible(false);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Dni = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        txt_Contraseña = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        background.setPreferredSize(new java.awt.Dimension(875, 814));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Centro de Asistencia de Emergencia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 620, 58));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 70));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setText("DNI:");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, 30));

        txt_Dni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_Dni.setForeground(new java.awt.Color(153, 153, 153));
        txt_Dni.setText("Ingrese su DNI");
        txt_Dni.setBorder(null);
        txt_Dni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_DniMousePressed(evt);
            }
        });
        background.add(txt_Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 380, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 390, 1));

        btnRegistrar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        background.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 130, 30));

        txt_Contraseña.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_Contraseña.setForeground(new java.awt.Color(153, 153, 153));
        txt_Contraseña.setText("Ingrese su contraseña");
        txt_Contraseña.setBorder(null);
        txt_Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ContraseñaMousePressed(evt);
            }
        });
        background.add(txt_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 380, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 390, 1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 30));

        txt_Nombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nombre.setText("Ingrese su nombre");
        txt_Nombre.setBorder(null);
        txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NombreMousePressed(evt);
            }
        });
        background.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 380, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 390, 1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, 30));

        txt_Telefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_Telefono.setForeground(new java.awt.Color(153, 153, 153));
        txt_Telefono.setText("Ingrese su telefono");
        txt_Telefono.setBorder(null);
        txt_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_TelefonoMousePressed(evt);
            }
        });
        background.add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 380, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 390, 1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setText("Telefono:");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 30));

        txt_Correo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txt_Correo.setForeground(new java.awt.Color(153, 153, 153));
        txt_Correo.setText("Ingrese su correo");
        txt_Correo.setBorder(null);
        txt_Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_CorreoMousePressed(evt);
            }
        });
        background.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 380, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 390, 1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("Correo:");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DniMousePressed
        if(txt_Dni.getText().equals("Ingrese su DNI")){
            txt_Dni.setText("");
            txt_Dni.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_DniMousePressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            /*/java.awt.Point location = this.getLocation();
            DataBaseConnection.pantallaUsuario.setLocation(location);

            DataBaseConnection.pantallaUsuario.setVisible(true);/*/
        if(txt_Dni.getText().length()==8){
            System.out.println("Registrando usuario...");
            Usuario user = new Usuario(txt_Dni.getText(), txt_Nombre.getText(),txt_Telefono.getText(),txt_Correo.getText(),txt_Contraseña.getText());
            insertarUsuario(user);
            limpiarCampos();
            //listarUsuarios();
        }else{
            System.out.println("Debe contener 8 caracteres");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txt_ContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ContraseñaMousePressed
        if(txt_Contraseña.getText().equals("Ingrese su contraseña")){
            txt_Contraseña.setText("");
            txt_Contraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_ContraseñaMousePressed

    private void txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreMousePressed
        if(txt_Nombre.getText().equals("Ingrese su nombre")){
            txt_Nombre.setText("");
            txt_Nombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_NombreMousePressed

    private void txt_TelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TelefonoMousePressed
        if(txt_Telefono.getText().equals("Ingrese su telefono")){
            txt_Telefono.setText("");
            txt_Telefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_TelefonoMousePressed

    private void txt_CorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CorreoMousePressed
        if(txt_Correo.getText().equals("Ingrese su correo")){
            txt_Correo.setText("");
            txt_Correo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_CorreoMousePressed

    private void insertarUsuario(Usuario user){
        try {
            DataAccesUsuario dao = new DataAccesUsuario(st,user,this);
            dao.insertarUsuario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    private void limpiarCampos() {
        txt_Dni.setText("");
        txt_Contraseña.setText("");
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        txt_Correo.setText("");
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txt_Contraseña;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Dni;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
