/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.DataAccesSolicitud;
import Conexion.DataAccesUsuario;
import Conexion.DataBaseConnection;
import Entidades.Solicitud;
import Entidades.Usuario;
import static Interfaz.Frm_Usuario.txt_dni;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Frm_Administrador extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private List<Usuario> usuariosList;
    private List<Solicitud> solicitudesList;
    private Object[] oSolicitudes = new Object[7];
    private Object[] oUsuarios = new Object[5];
    
    private DefaultTableModel dtmSolicitudes;
    private DefaultTableModel dtmUsuarios;
    /**
     * Creates new form Frm_Administrador
     */
    public Frm_Administrador() {
        try {
            //Obtener la conexión centralizada
            conexion = DataBaseConnection.getInstancia().getConexion();
            st = conexion.createStatement();
            initComponents();
            dtmSolicitudes = (DefaultTableModel) t_Solicitudes.getModel();
            dtmUsuarios = (DefaultTableModel) t_Usuarios.getModel();
            panelGestionUsuario.setVisible(false);
            panelGestionEmergencia.setVisible(false);
        } catch (SQLException e) {
            System.err.println("Error al crear el Statement: " + e.getMessage());
        }
        this.setSize(1010,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelGestionEmergencia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_Solicitudes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panelGestionUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_Usuarios = new javax.swing.JTable();
        panelOpciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JButton();
        btnGestionEmergencia = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnGestionUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setDoubleBuffered(false);
        background.setPreferredSize(new java.awt.Dimension(810, 490));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGestionEmergencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setText("Gestion de Emergencia");
        panelGestionEmergencia.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 30));

        t_Solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI Usuario", "ID Emergencia", "Descripcion", "Direccion", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_Solicitudes);
        if (t_Solicitudes.getColumnModel().getColumnCount() > 0) {
            t_Solicitudes.getColumnModel().getColumn(0).setResizable(false);
            t_Solicitudes.getColumnModel().getColumn(1).setResizable(false);
            t_Solicitudes.getColumnModel().getColumn(2).setResizable(false);
            t_Solicitudes.getColumnModel().getColumn(3).setResizable(false);
            t_Solicitudes.getColumnModel().getColumn(6).setResizable(false);
        }

        panelGestionEmergencia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 670, 340));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setText("Solicitudes de Emergencia");
        panelGestionEmergencia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 30));

        background.add(panelGestionEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 710, 490));

        panelGestionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setText("Lista de Usuarios");
        panelGestionUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setText("Gestion de Usuario");
        panelGestionUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 30));

        t_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Telefono", "Correo", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(t_Usuarios);
        if (t_Usuarios.getColumnModel().getColumnCount() > 0) {
            t_Usuarios.getColumnModel().getColumn(0).setResizable(false);
            t_Usuarios.getColumnModel().getColumn(1).setResizable(false);
            t_Usuarios.getColumnModel().getColumn(2).setResizable(false);
            t_Usuarios.getColumnModel().getColumn(3).setResizable(false);
            t_Usuarios.getColumnModel().getColumn(4).setResizable(false);
        }

        panelGestionUsuario.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 670, 340));

        background.add(panelGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 710, 490));

        panelOpciones.setBackground(new java.awt.Color(0, 153, 153));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Asistencia de Emergencia");
        panelOpciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 40));

        btnPanel.setBackground(new java.awt.Color(0, 125, 118));
        btnPanel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel.setText("Panel");
        btnPanel.setBorder(null);
        btnPanel.setContentAreaFilled(false);
        btnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanel.setDefaultCapable(false);
        btnPanel.setFocusPainted(false);
        btnPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelMouseExited(evt);
            }
        });
        btnPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelActionPerformed(evt);
            }
        });
        panelOpciones.add(btnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 126, -1));

        btnGestionEmergencia.setBackground(new java.awt.Color(0, 125, 118));
        btnGestionEmergencia.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnGestionEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEmergencia.setText("Gestion de Emergencia");
        btnGestionEmergencia.setBorder(null);
        btnGestionEmergencia.setContentAreaFilled(false);
        btnGestionEmergencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionEmergencia.setDefaultCapable(false);
        btnGestionEmergencia.setFocusPainted(false);
        btnGestionEmergencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionEmergencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionEmergenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionEmergenciaMouseExited(evt);
            }
        });
        btnGestionEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmergenciaActionPerformed(evt);
            }
        });
        panelOpciones.add(btnGestionEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        btnConfiguracion.setBackground(new java.awt.Color(0, 125, 118));
        btnConfiguracion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("Configuracion del sistema");
        btnConfiguracion.setActionCommand("Configuracion del sistema");
        btnConfiguracion.setBorder(null);
        btnConfiguracion.setContentAreaFilled(false);
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguracion.setDefaultCapable(false);
        btnConfiguracion.setFocusPainted(false);
        btnConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseExited(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        panelOpciones.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        btnGestionUsuario.setBackground(new java.awt.Color(0, 125, 118));
        btnGestionUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnGestionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUsuario.setText("Gestion de Usuario");
        btnGestionUsuario.setBorder(null);
        btnGestionUsuario.setContentAreaFilled(false);
        btnGestionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionUsuario.setDefaultCapable(false);
        btnGestionUsuario.setFocusPainted(false);
        btnGestionUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionUsuarioMouseExited(evt);
            }
        });
        btnGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioActionPerformed(evt);
            }
        });
        panelOpciones.add(btnGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 126, -1));

        background.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 510));

        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelMouseEntered
        btnPanel.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnPanelMouseEntered

    private void btnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelMouseExited
        btnPanel.setForeground(Color.white);
    }//GEN-LAST:event_btnPanelMouseExited

    private void btnPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelActionPerformed


    }//GEN-LAST:event_btnPanelActionPerformed

    private void btnGestionEmergenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionEmergenciaMouseEntered
        btnGestionEmergencia.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnGestionEmergenciaMouseEntered

    private void btnGestionEmergenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionEmergenciaMouseExited
        btnGestionEmergencia.setForeground(Color.white);
    }//GEN-LAST:event_btnGestionEmergenciaMouseExited

    private void btnGestionEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmergenciaActionPerformed
        panelGestionUsuario.setVisible(false);
        panelGestionEmergencia.setVisible(true);
        listarSolicitudes();
    }//GEN-LAST:event_btnGestionEmergenciaActionPerformed

    private void btnConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseEntered
        btnConfiguracion.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnConfiguracionMouseEntered

    private void btnConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseExited
        btnConfiguracion.setForeground(Color.white);
    }//GEN-LAST:event_btnConfiguracionMouseExited

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed

    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnGestionUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionUsuarioMouseEntered
        btnGestionUsuario.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnGestionUsuarioMouseEntered

    private void btnGestionUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionUsuarioMouseExited
        btnGestionUsuario.setForeground(Color.white);
    }//GEN-LAST:event_btnGestionUsuarioMouseExited

    private void btnGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioActionPerformed
        panelGestionEmergencia.setVisible(false);
        panelGestionUsuario.setVisible(true);
        listarUsuarios();
    }//GEN-LAST:event_btnGestionUsuarioActionPerformed
    private void listarSolicitudes(){
        try {
            dtmUsuarios.setRowCount(0);
            DataAccesSolicitud das = new DataAccesSolicitud(st);
            solicitudesList = das.getListaSolicitudes();
            
            dtmSolicitudes.setRowCount(0);
            for (Solicitud solicitud : solicitudesList) {
                oSolicitudes[0] = solicitud.getId();
                oSolicitudes[1] = solicitud.getDni_Usuario();
                oSolicitudes[2] = solicitud.getId_emergencia();
                oSolicitudes[3] = solicitud.getDescripcion();
                oSolicitudes[4] = solicitud.getDireccion();
                oSolicitudes[5] = solicitud.getFecha().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                oSolicitudes[6] = solicitud.getEstado();
                dtmSolicitudes.addRow(oSolicitudes);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las solicitudes: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void listarUsuarios(){
        try {
            dtmUsuarios.setRowCount(0);

            DataAccesUsuario dau = new DataAccesUsuario(st);
            usuariosList = dau.getListaUsuarios();

            for (Usuario usuario : usuariosList) {
                oUsuarios[0] = usuario.getDni();
                oUsuarios[1] = usuario.getNombre();
                oUsuarios[2] = usuario.getTelefono();
                oUsuarios[3] = usuario.getCorreo();
                oUsuarios[4] = usuario.getContraseña();
                dtmUsuarios.addRow(oUsuarios);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnGestionEmergencia;
    private javax.swing.JButton btnGestionUsuario;
    private javax.swing.JButton btnPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelGestionEmergencia;
    private javax.swing.JPanel panelGestionUsuario;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTable t_Solicitudes;
    private javax.swing.JTable t_Usuarios;
    // End of variables declaration//GEN-END:variables
}
