/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.DataAccesUsuario;
import Conexion.DataBaseConnection;
import Entidades.Usuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Frm_CambiarContra extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    /**
     * Creates new form Frm_Contraseña
     */
    public Frm_CambiarContra() {
        try {
            conexion = DataBaseConnection.getInstancia().getConexion();
            st = conexion.createStatement();
            initComponents();
            this.setSize(825,500);
        } catch (SQLException ex) {
            Logger.getLogger(Frm_CambiarContra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNuevaContraseña = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAntiguaContraseña = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nueva Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 240, 30));

        txtNuevaContraseña.setForeground(new java.awt.Color(153, 153, 153));
        txtNuevaContraseña.setText("*******");
        txtNuevaContraseña.setBorder(null);
        txtNuevaContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNuevaContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(txtNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 300, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, 2));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Antigua Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 240, 30));

        txtAntiguaContraseña.setForeground(new java.awt.Color(153, 153, 153));
        txtAntiguaContraseña.setText("*******");
        txtAntiguaContraseña.setBorder(null);
        txtAntiguaContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAntiguaContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(txtAntiguaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 300, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, 2));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText("DNI:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 30));

        txtDni.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDni.setBorder(null);
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 180, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 122, 180, 1));

        jButton1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 0, 800, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevaContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevaContraseñaMousePressed
        txtNuevaContraseña.setText("");
        txtNuevaContraseña.setForeground(Color.black);
    }//GEN-LAST:event_txtNuevaContraseñaMousePressed

    private void txtAntiguaContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAntiguaContraseñaMousePressed
        txtAntiguaContraseña.setText("");
        txtAntiguaContraseña.setForeground(Color.black);
    }//GEN-LAST:event_txtAntiguaContraseñaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario usuarioAntiguo = new Usuario(txtDni.getText(),txtAntiguaContraseña.getText());
        DataAccesUsuario dau; 
        dau = new DataAccesUsuario(st, usuarioAntiguo);
        try {
            boolean encontrado = dau.buscarUsuario();
            if (encontrado){
                Usuario usuarioNuevo = new Usuario(txtDni.getText(),txtNuevaContraseña.getText());
                dau = new DataAccesUsuario(st, usuarioNuevo);
                dau.actualizarContraseña();
                JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
                limpiar();
            }else{
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frm_CambiarContra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void limpiar(){
        txtDni.setText("");
        txtAntiguaContraseña.setText("");
        txtNuevaContraseña.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAntiguaContraseña;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNuevaContraseña;
    // End of variables declaration//GEN-END:variables
}
